/**
 * HTML report generator for GitLab-wide scans.
 *
 * Generates a self-contained, single-file HTML report that can be
 * attached to an email or opened in any browser. No external deps.
 */

import type { GitLabScanResult, GitLabRepoScanResult } from '../gitlab/types.js';
import type { Severity, Vulnerability } from '../core/types.js';

export class HtmlReporter {
  readonly name = 'html';

  generate(result: GitLabScanResult): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Verimu Security Report — ${this.escapeHtml(result.instanceUrl)}</title>
${this.styles()}
</head>
<body>
<div class="container">
  ${this.header(result)}
  ${this.summaryCards(result)}
  ${this.severityChart(result)}
  ${this.topVulnerabilities(result)}
  ${this.repoBreakdown(result)}
  ${this.ecosystemBreakdown(result)}
  ${this.craTimeline(result)}
  ${this.footer(result)}
</div>
</body>
</html>`;
  }

  // ─── Sections ─────────────────────────────────────────────

  private header(result: GitLabScanResult): string {
    const date = new Date(result.scannedAt).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    });

    return `
  <header>
    <div class="brand">
      <div class="logo">V</div>
      <div>
        <h1>Security posture report</h1>
        <p class="subtitle">${this.escapeHtml(result.instanceUrl)} — ${date}</p>
      </div>
    </div>
    <p class="intro">
      This report summarizes the current vulnerability landscape across
      <strong>${result.summary.totalRepos} repositories</strong> containing
      <strong>${result.summary.totalDependencies.toLocaleString()} dependencies</strong>.
      Generated by <a href="https://verimu.com">Verimu</a> CRA Compliance Scanner.
    </p>
  </header>`;
  }

  private summaryCards(result: GitLabScanResult): string {
    const s = result.summary;
    const vulnRepoPercent = s.totalRepos > 0
      ? Math.round((s.reposWithVulnerabilities / s.totalRepos) * 100)
      : 0;

    return `
  <section class="cards">
    <div class="card">
      <div class="card-value">${s.totalRepos}</div>
      <div class="card-label">Repos scanned</div>
    </div>
    <div class="card">
      <div class="card-value">${s.totalDependencies.toLocaleString()}</div>
      <div class="card-label">Total dependencies</div>
    </div>
    <div class="card card-danger">
      <div class="card-value">${s.totalVulnerabilities}</div>
      <div class="card-label">Vulnerabilities found</div>
    </div>
    <div class="card ${vulnRepoPercent > 50 ? 'card-danger' : vulnRepoPercent > 25 ? 'card-warn' : ''}">
      <div class="card-value">${vulnRepoPercent}%</div>
      <div class="card-label">Repos with vulns</div>
    </div>
  </section>`;
  }

  private severityChart(result: GitLabScanResult): string {
    const s = result.summary;
    const total = s.totalVulnerabilities || 1;

    const bars = [
      { label: 'Critical', count: s.critical, cls: 'sev-critical' },
      { label: 'High', count: s.high, cls: 'sev-high' },
      { label: 'Medium', count: s.medium, cls: 'sev-medium' },
      { label: 'Low', count: s.low, cls: 'sev-low' },
    ];

    const barHtml = bars.map((b) => {
      const width = Math.max(2, (b.count / total) * 100);
      return `
      <div class="bar-row">
        <span class="bar-label">${b.label}</span>
        <div class="bar-track">
          <div class="bar-fill ${b.cls}" style="width: ${width}%"></div>
        </div>
        <span class="bar-count">${b.count}</span>
      </div>`;
    }).join('');

    return `
  <section>
    <h2>Severity breakdown</h2>
    <div class="chart">${barHtml}</div>
    ${s.exploitedInWild > 0 ? `
    <div class="alert alert-critical">
      <strong>⚠ ${s.exploitedInWild} vulnerabilit${s.exploitedInWild === 1 ? 'y' : 'ies'} actively exploited in the wild.</strong>
      Under the EU Cyber Resilience Act, actively exploited vulnerabilities require
      notification to ENISA within 24 hours of awareness.
    </div>` : ''}
  </section>`;
  }

  private topVulnerabilities(result: GitLabScanResult): string {
    if (result.topVulnerabilities.length === 0) {
      return `
  <section>
    <h2>Vulnerabilities</h2>
    <p class="empty">No known vulnerabilities detected. Nice work.</p>
  </section>`;
    }

    // Show top 30
    const top = result.topVulnerabilities.slice(0, 30);

    const rows = top.map((vuln) => `
      <tr>
        <td><span class="sev-badge ${this.sevClass(vuln.severity)}">${vuln.severity}</span></td>
        <td class="vuln-id">${this.escapeHtml(vuln.id)}</td>
        <td>${this.escapeHtml(vuln.summary.slice(0, 120))}</td>
        <td>${vuln.fixedVersion ? this.escapeHtml(vuln.fixedVersion) : '<span class="no-fix">none</span>'}</td>
        <td>${vuln.affectedRepos.length}</td>
        <td>${vuln.exploitedInWild ? '<span class="exploited">YES</span>' : ''}</td>
      </tr>`
    ).join('');

    return `
  <section>
    <h2>Top vulnerabilities</h2>
    <p class="section-desc">Sorted by severity, then by number of affected repositories.</p>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Severity</th>
            <th>ID</th>
            <th>Summary</th>
            <th>Fix</th>
            <th>Repos</th>
            <th>Exploited</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  </section>`;
  }

  private repoBreakdown(result: GitLabScanResult): string {
    const repos = result.scannedRepos
      .filter((r) => r.reports.length > 0)
      .sort((a, b) => {
        const aVulns = a.reports.reduce((s, r) => s + r.summary.totalVulnerabilities, 0);
        const bVulns = b.reports.reduce((s, r) => s + r.summary.totalVulnerabilities, 0);
        return bVulns - aVulns;
      });

    const rows = repos.map((r) => {
      const s = r.reports.reduce((acc, rpt) => ({ totalVulnerabilities: acc.totalVulnerabilities + rpt.summary.totalVulnerabilities, critical: acc.critical + rpt.summary.critical, high: acc.high + rpt.summary.high, medium: acc.medium + rpt.summary.medium, low: acc.low + rpt.summary.low, totalDependencies: acc.totalDependencies + rpt.summary.totalDependencies }), { totalVulnerabilities: 0, critical: 0, high: 0, medium: 0, low: 0, totalDependencies: 0 });
      const vulnBadge = s.totalVulnerabilities > 0
        ? `<span class="sev-badge ${s.critical > 0 ? 'sev-critical' : s.high > 0 ? 'sev-high' : s.medium > 0 ? 'sev-medium' : 'sev-low'}">${s.totalVulnerabilities}</span>`
        : '<span class="clean">clean</span>';

      return `
      <tr>
        <td class="repo-name">${this.escapeHtml(r.project.path_with_namespace)}</td>
        <td>${r.reports.map(rpt => rpt.project.ecosystem).filter((v, i, a) => a.indexOf(v) === i).join(', ')}</td>
        <td>${s.totalDependencies}</td>
        <td>${vulnBadge}</td>
        <td>${s.critical}</td>
        <td>${s.high}</td>
        <td>${s.medium}</td>
        <td>${s.low}</td>
      </tr>`;
    }).join('');

    return `
  <section>
    <h2>Repository breakdown</h2>
    <p class="section-desc">${repos.length} repositories with dependency lockfiles.</p>
    <div class="table-wrap">
      <table>
        <thead>
          <tr>
            <th>Repository</th>
            <th>Ecosystem</th>
            <th>Deps</th>
            <th>Vulns</th>
            <th>Crit</th>
            <th>High</th>
            <th>Med</th>
            <th>Low</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  </section>`;
  }

  private ecosystemBreakdown(result: GitLabScanResult): string {
    const eco = result.summary.ecosystemBreakdown;
    if (Object.keys(eco).length === 0) return '';

    const items = Object.entries(eco)
      .sort((a, b) => b[1] - a[1])
      .map(([name, count]) => `
        <div class="eco-item">
          <span class="eco-name">${name}</span>
          <span class="eco-count">${count} repo${count !== 1 ? 's' : ''}</span>
        </div>`)
      .join('');

    return `
  <section>
    <h2>Ecosystem distribution</h2>
    <div class="eco-grid">${items}</div>
  </section>`;
  }

  private craTimeline(result: GitLabScanResult): string {
    const s = result.summary;
    if (s.totalVulnerabilities === 0) return '';

    return `
  <section>
    <h2>CRA compliance implications</h2>
    <div class="cra-box">
      <p>The <strong>EU Cyber Resilience Act</strong> (Regulation 2024/2847) establishes
      mandatory cybersecurity requirements for products with digital elements.
      Key obligations relevant to this scan:</p>
      <ul>
        <li><strong>Article 14(2):</strong> Manufacturers must identify and document
        vulnerabilities, including in third-party components (your dependencies).</li>
        <li><strong>Article 14(4):</strong> Actively exploited vulnerabilities must be
        reported to ENISA within 24 hours of awareness${s.exploitedInWild > 0
          ? ` — <strong class="text-danger">${s.exploitedInWild} found in this scan</strong>` : ''}.</li>
        <li><strong>Article 14(3):</strong> Security updates must be provided free of charge
        for the support period.</li>
        <li><strong>Annex I, Part II(1):</strong> An SBOM documenting all components must
        be maintained — Verimu generates these in CycloneDX, SPDX, and SWID formats.</li>
      </ul>
      <p class="cra-note">Full enforcement begins <strong>11 December 2027</strong>.
      Vulnerability reporting obligations apply from <strong>11 September 2026</strong>.</p>
    </div>
  </section>`;
  }

  private footer(result: GitLabScanResult): string {
    const duration = (result.durationMs / 1000).toFixed(1);
    return `
  <footer>
    <p>Generated by <a href="https://verimu.com">Verimu</a> CRA Compliance Scanner
    in ${duration}s on ${new Date(result.scannedAt).toISOString()}</p>
    <p class="footer-cta">
      Continuous monitoring, SBOM management, and CRA compliance dashboards available at
      <a href="https://app.verimu.com">app.verimu.com</a>
    </p>
  </footer>`;
  }

  // ─── Styling ──────────────────────────────────────────────

  private styles(): string {
    return `<style>
  :root {
    --bg: #ffffff; --bg2: #f7f8fa; --text: #1a1a2e; --text2: #555770;
    --border: #e2e4ea; --accent: #4f46e5; --accent-light: #eef2ff;
    --crit: #dc2626; --crit-bg: #fef2f2;
    --high: #ea580c; --high-bg: #fff7ed;
    --med: #d97706; --med-bg: #fffbeb;
    --low: #2563eb; --low-bg: #eff6ff;
    --green: #16a34a; --green-bg: #f0fdf4;
    --radius: 8px; --radius-lg: 12px;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0f0f1a; --bg2: #1a1a2e; --text: #e4e4f0; --text2: #9595ad;
      --border: #2a2a40; --accent: #818cf8; --accent-light: #1e1b4b;
      --crit-bg: #2a0a0a; --high-bg: #2a1a0a; --med-bg: #2a2200; --low-bg: #0a1a2e;
      --green-bg: #0a2a1a;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
    background: var(--bg); color: var(--text); line-height: 1.6; }
  .container { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }

  /* Header */
  header { margin-bottom: 2rem; }
  .brand { display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem; }
  .logo { width: 48px; height: 48px; background: var(--accent); color: #fff;
    border-radius: var(--radius); display: flex; align-items: center; justify-content: center;
    font-size: 24px; font-weight: 700; }
  h1 { font-size: 22px; font-weight: 600; }
  .subtitle { color: var(--text2); font-size: 14px; }
  .intro { color: var(--text2); font-size: 15px; max-width: 700px; }

  /* Cards */
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 12px; margin-bottom: 2rem; }
  .card { background: var(--bg2); border-radius: var(--radius-lg); padding: 1.25rem;
    border: 1px solid var(--border); }
  .card-value { font-size: 28px; font-weight: 700; }
  .card-label { font-size: 13px; color: var(--text2); margin-top: 4px; }
  .card-danger .card-value { color: var(--crit); }
  .card-warn .card-value { color: var(--med); }

  /* Sections */
  section { margin-bottom: 2.5rem; }
  h2 { font-size: 18px; font-weight: 600; margin-bottom: 0.75rem; }
  .section-desc { color: var(--text2); font-size: 14px; margin-bottom: 1rem; }
  .empty { color: var(--green); font-weight: 500; }

  /* Bar chart */
  .chart { max-width: 500px; }
  .bar-row { display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }
  .bar-label { width: 60px; font-size: 13px; color: var(--text2); text-align: right; }
  .bar-track { flex: 1; height: 24px; background: var(--bg2); border-radius: 4px;
    overflow: hidden; border: 1px solid var(--border); }
  .bar-fill { height: 100%; border-radius: 3px; transition: width 0.3s; }
  .bar-count { width: 36px; font-size: 14px; font-weight: 600; }
  .sev-critical, .bar-fill.sev-critical { background: var(--crit); color: #fff; }
  .sev-high, .bar-fill.sev-high { background: var(--high); color: #fff; }
  .sev-medium, .bar-fill.sev-medium { background: var(--med); color: #fff; }
  .sev-low, .bar-fill.sev-low { background: var(--low); color: #fff; }

  /* Tables */
  .table-wrap { overflow-x: auto; border: 1px solid var(--border); border-radius: var(--radius-lg); }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: var(--bg2); font-weight: 600; font-size: 12px; text-transform: uppercase;
    letter-spacing: 0.5px; color: var(--text2); padding: 10px 12px; text-align: left;
    border-bottom: 1px solid var(--border); }
  td { padding: 10px 12px; border-bottom: 1px solid var(--border); vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: var(--bg2); }
  .repo-name { font-weight: 500; font-size: 13px; }
  .vuln-id { font-family: monospace; font-size: 12px; white-space: nowrap; }

  /* Badges */
  .sev-badge { display: inline-block; padding: 2px 8px; border-radius: 4px;
    font-size: 11px; font-weight: 700; text-transform: uppercase; }
  .clean { color: var(--green); font-size: 12px; font-weight: 500; }
  .no-fix { color: var(--text2); font-size: 12px; }
  .exploited { color: var(--crit); font-weight: 700; font-size: 12px; }

  /* Alert */
  .alert { padding: 1rem 1.25rem; border-radius: var(--radius); margin-top: 1rem; font-size: 14px; }
  .alert-critical { background: var(--crit-bg); border: 1px solid var(--crit); color: var(--crit); }

  /* Ecosystem grid */
  .eco-grid { display: flex; flex-wrap: wrap; gap: 8px; }
  .eco-item { background: var(--bg2); border: 1px solid var(--border); border-radius: var(--radius);
    padding: 8px 16px; display: flex; align-items: center; gap: 8px; }
  .eco-name { font-weight: 600; font-size: 14px; }
  .eco-count { color: var(--text2); font-size: 13px; }

  /* CRA */
  .cra-box { background: var(--accent-light); border: 1px solid var(--accent);
    border-radius: var(--radius-lg); padding: 1.5rem; font-size: 14px; }
  .cra-box ul { margin: 0.75rem 0; padding-left: 1.5rem; }
  .cra-box li { margin-bottom: 0.5rem; }
  .cra-note { margin-top: 1rem; font-weight: 600; }
  .text-danger { color: var(--crit); }

  /* Footer */
  footer { border-top: 1px solid var(--border); padding-top: 1.5rem; margin-top: 2rem;
    color: var(--text2); font-size: 13px; }
  .footer-cta { margin-top: 0.5rem; }

  @media print {
    .container { max-width: 100%; }
    .card { break-inside: avoid; }
  }
</style>`;
  }

  // ─── Helpers ──────────────────────────────────────────────

  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  private sevClass(severity: Severity): string {
    const map: Record<Severity, string> = {
      CRITICAL: 'sev-critical',
      HIGH: 'sev-high',
      MEDIUM: 'sev-medium',
      LOW: 'sev-low',
      UNKNOWN: 'sev-low',
    };
    return map[severity] ?? 'sev-low';
  }
}
