import { readFile } from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import type { DependencyScanner } from '../scanner.interface.js';
import type { Dependency, Ecosystem, ScanResult } from '../../core/types.js';
import { LockfileParseError } from '../../core/errors.js';

/**
 * C# / NuGet dependency scanner.
 *
 * Parses `packages.lock.json` (NuGet lock file, generated by
 * `dotnet restore --use-lock-file`) to extract the full resolved
 * dependency tree. The lock file itself tracks Direct vs Transitive.
 *
 * Lock file format (NuGet v1):
 * ```json
 * {
 *   "version": 1,
 *   "dependencies": {
 *     "net8.0": {
 *       "PackageName": {
 *         "type": "Direct" | "Transitive",
 *         "resolved": "13.0.3",
 *         "contentHash": "..."
 *       }
 *     }
 *   }
 * }
 * ```
 */
export class NugetScanner implements DependencyScanner {
  readonly ecosystem: Ecosystem = 'nuget';
  readonly lockfileNames = ['packages.lock.json'];

  async detect(projectPath: string): Promise<string | null> {
    const lockfilePath = path.join(projectPath, 'packages.lock.json');
    return existsSync(lockfilePath) ? lockfilePath : null;
  }

  async scan(projectPath: string, lockfilePath: string): Promise<ScanResult> {
    const lockfileRaw = await readFile(lockfilePath, 'utf-8');

    let lockfile: NugetLockfile;
    try {
      lockfile = JSON.parse(lockfileRaw);
    } catch {
      throw new LockfileParseError(lockfilePath, 'Invalid JSON');
    }

    if (!lockfile.dependencies) {
      throw new LockfileParseError(lockfilePath, 'Missing "dependencies" field');
    }

    const dependencies = this.parseLockfile(lockfile);

    return {
      projectPath,
      ecosystem: 'nuget',
      dependencies,
      lockfilePath,
      scannedAt: new Date().toISOString(),
    };
  }

  /**
   * Parses packages.lock.json and extracts dependencies across all
   * target frameworks. Deduplicates by package name (keeps highest version
   * if the same package appears under multiple frameworks).
   */
  private parseLockfile(lockfile: NugetLockfile): Dependency[] {
    const depMap = new Map<string, Dependency>();

    for (const [_framework, packages] of Object.entries(lockfile.dependencies)) {
      for (const [name, info] of Object.entries(packages)) {
        if (!info.resolved) continue;

        // "Direct" in the lock file means it's a PackageReference in .csproj
        const isDirect = info.type === 'Direct';

        const existing = depMap.get(name);
        if (!existing) {
          depMap.set(name, {
            name,
            version: info.resolved,
            direct: isDirect,
            ecosystem: 'nuget',
            purl: this.buildPurl(name, info.resolved),
          });
        }
        // If already seen, keep the direct flag if either occurrence is direct
        else if (isDirect && !existing.direct) {
          existing.direct = true;
        }
      }
    }

    return Array.from(depMap.values());
  }

  /**
   * Builds a purl for a NuGet package.
   * NuGet purls are straightforward: pkg:nuget/Name@Version
   */
  private buildPurl(name: string, version: string): string {
    return `pkg:nuget/${name}@${version}`;
  }
}

// ─── Types for packages.lock.json parsing ────────────────────────

interface NugetLockfile {
  version?: number;
  dependencies: Record<string, Record<string, NugetLockfileEntry>>;
}

interface NugetLockfileEntry {
  type?: 'Direct' | 'Transitive';
  resolved?: string;
  contentHash?: string;
  dependencies?: Record<string, string>;
}
