name: Push to Verimu repos on Gitlab and Bitbucket

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: send to gitlab 
        run: | 
              git fetch --unshallow
              git remote set-url origin ${{ secrets.VERIMU_GITLAB_REPO }}
              git push origin ${{ vars.GITLAB_BRANCH }}
              git remote set-url origin ${{ secrets.VERIMU_BITBUCKET_REPO }}
              git push origin ${{ vars.BITBUCKET_BRANCH }}
