name: Push to Verimu repos on Gitlab and Bitbucket

on:
  push:
    branches: [main]


jobs:
  pushing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send to Gitlab and Bitbucket
        run: | 
              git fetch --unshallow
              git remote set-url origin ${{ secrets.VERIMU_GITLAB_REPO }}
              git push origin ${{ vars.GITLAB_BRANCH }}
              git remote set-url origin ${{ secrets.VERIMU_BITBUCKET_REPO }}
              git push origin ${{ vars.BITBUCKET_BRANCH }}
